sonar.projectKey=elderpinq-auth-service
sonar.projectName=elderpinq-auth-service
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
